Repository KW-ClassLog/ClassLog, pull requests merged in 2025-09, with the labels that each got.

#294 ✨ Feat/#280 클래스 상세 마크업 + api 연동
  frontend/app/student/class-detail/[classId]/_components/ClassInfoSection/ClassInfoSection.module.scss
  frontend/app/student/class-detail/[classId]/_components/ClassInfoSection/ClassInfoSection.tsx
  frontend/app/student/class-detail/[classId]/_components/LectureList/LectureList.module.scss
  frontend/app/student/class-detail/[classId]/_components/LectureList/LectureList.tsx
  frontend/app/student/class-detail/[classId]/_components/LectureListAndNote/LectureListAndNote.module.scss
  frontend/app/student/class-detail/[classId]/_components/LectureListAndNote/LectureListAndNote.tsx
  frontend/app/student/class-detail/[classId]/_components/LectureNote/LectureNote.module.scss
  frontend/app/student/class-detail/[classId]/_components/LectureNote/LectureNote.tsx
  frontend/app/student/class-detail/[classId]/page.tsx
  frontend/app/student/class/_components/ClassListSection/ClassListSection.tsx
  frontend/components/Header/Student/BackWithProfileHeader/BackWithProfileHeader.module.scss
  frontend/components/Tab/Tab.module.scss
Labels: ✨ Feat

#310 ✨ Feat/#309 학생용 강의 조회
  backend/src/main/java/org/example/backend/domain/lecture/controller/LectureController.java
  backend/src/main/java/org/example/backend/domain/lecture/dto/response/ClassNameResponseDTO.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureService.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureStudentService.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureStudentServiceImpl.java
  backend/src/main/java/org/example/backend/domain/quiz/repository/QuizRepository.java
Labels: ✨ Feat

#308 ✨ Feat/#307 강의 id로 클래스 제목 조회 api 구현
  backend/src/main/java/org/example/backend/domain/lecture/controller/LectureController.java
  backend/src/main/java/org/example/backend/domain/lecture/dto/response/ClassNameResponseDTO.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureService.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ✨ Feat

#312 📦 Chore/#311 local용 docker compose 파일 작성
  docker-compose.local.yml
Labels: 📦 Chore

#313 ✨ Feat/#304 실시간 채팅 기능 구현
  backend/build.gradle
  backend/src/main/java/org/example/backend/domain/question/controller/ChatController.java
  backend/src/main/java/org/example/backend/domain/question/dto/request/MessageRequestDTO.java
  backend/src/main/java/org/example/backend/domain/question/exception/QuestionErrorCode.java
  backend/src/main/java/org/example/backend/domain/question/service/ChatService.java
  backend/src/main/java/org/example/backend/domain/question/service/ChatServiceImpl.java
  backend/src/main/java/org/example/backend/global/redis/RedisConfig.java
  backend/src/main/java/org/example/backend/global/redis/RedisMessageSubscriber.java
  backend/src/main/java/org/example/backend/global/security/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/security/filter/JWTFilter.java
  backend/src/main/java/org/example/backend/global/websocket/StompChannelInterceptor.java
  backend/src/main/java/org/example/backend/global/websocket/StompPrincipal.java
  backend/src/main/java/org/example/backend/global/websocket/WebSocketConfig.java
Labels: ✨ Feat

#318 ✨ Feat/#303 선생님 알림 조회, 설정에서 알림 설정 api 연동
  backend/src/main/java/org/example/backend/domain/notification/controller/NotificationController.java
  backend/src/main/java/org/example/backend/domain/notification/converter/NotificationConverter.java
  backend/src/main/java/org/example/backend/domain/notification/dto/response/NotificationResponseDTO.java
  backend/src/main/java/org/example/backend/domain/notification/entity/Notification.java
  backend/src/main/java/org/example/backend/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/org/example/backend/domain/notification/service/NotificationService.java
  backend/src/main/java/org/example/backend/domain/notification/service/NotificationServiceImpl.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/controller/NotificationSettingController.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/converter/NotificationSettingConverter.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/dto/request/NotificationSettingPatchRequest.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/dto/response/NotificationSettingResponseDTO.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/entity/NotificationSetting.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/repository/NotificationSettingRepository.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/service/NotificationSettingService.java
  backend/src/main/java/org/example/backend/domain/notificationSetting/service/NotificationSettingServiceImpl.java
  frontend/api/notifications/fetchNotification.ts
  frontend/api/notifications/fetchNotificationSetting.ts
  frontend/api/notifications/updateNotificationSetting.ts
  frontend/app/teacher/notification/page.module.scss
  frontend/app/teacher/notification/page.tsx
  frontend/app/teacher/setting/page.module.scss
  frontend/app/teacher/setting/page.tsx
  frontend/components/Header/Teacher/TeacherHeader.tsx
  frontend/constants/routes.ts
Labels: ✨ Feat

#326 🐛 Fix/ #324 s3 오류
  backend/src/main/java/org/example/backend/global/S3/exception/S3ErrorCode.java
  backend/src/main/java/org/example/backend/global/S3/service/S3Service.java
Labels: 🐛 Bug
