Repository KW-ClassLog/ClassLog, pull requests merged in 2025-08, with the labels that each got.

#254 ✨ Feat/#252 학생용 퀴즈 문제 조회
  backend/src/main/java/org/example/backend/domain/option/dto/response/OptionResponseDTO.java
  backend/src/main/java/org/example/backend/domain/quiz/controller/QuizController.java
  backend/src/main/java/org/example/backend/domain/quiz/dto/response/QuizListResponseDTO.java
  backend/src/main/java/org/example/backend/domain/quiz/exception/QuizErrorCode.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizService.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizServiceImpl.java
Labels: ✨ Feat

#260 :recycle: Refactor/#259 입장코드 확인할 때 classId 필드 응답에 추가
  backend/src/main/java/org/example/backend/domain/classroom/controller/ClassroomController.java
  backend/src/main/java/org/example/backend/domain/classroom/dto/response/EntryCodeVerifyResponseDTO.java
Labels: ♻️ Refactor

#256 ♻️ Refactor/#255 도커 AI 이미지 변경
  backend/docker-compose.yml
Labels: ♻️ Refactor

#253 ✨ Feat/#145 카카오 로그인 기능
  backend/src/main/java/org/example/backend/BackendApplication.java
  backend/src/main/java/org/example/backend/domain/user/controller/UserController.java
  backend/src/main/java/org/example/backend/domain/user/converter/UserConverter.java
  backend/src/main/java/org/example/backend/domain/user/dto/request/OnboardingRequestDTO.java
  backend/src/main/java/org/example/backend/domain/user/dto/response/LoginResponseDTO.java
  backend/src/main/java/org/example/backend/domain/user/entity/Role.java
  backend/src/main/java/org/example/backend/domain/user/entity/User.java
  backend/src/main/java/org/example/backend/domain/user/exception/UserErrorCode.java
  backend/src/main/java/org/example/backend/domain/user/service/AuthService.java
  backend/src/main/java/org/example/backend/domain/user/service/AuthServiceImpl.java
  backend/src/main/java/org/example/backend/global/security/auth/CustomUserDetails.java
  backend/src/main/java/org/example/backend/global/security/config/SecurityConfig.java
  backend/src/main/java/org/example/backend/global/security/filter/JWTFilter.java
  backend/src/main/resources/application.properties
Labels: ✨ Feat

#269 ✨ Feat/#264 퀴즈 제출, 채점
  backend/docker-compose.yml
  backend/dump.rdb
  backend/src/main/java/org/example/backend/domain/quiz/exception/QuizErrorCode.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/controller/QuizAnswerController.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/converter/QuizAnswerConverter.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/dto/request/QuizSubmitRequestDTO.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/dto/response/QuizSubmitResponseDTO.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/repository/QuizAnswerRepository.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/service/QuizSubmitService.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/service/QuizSubmitServiceImpl.java
Labels: ✨ Feat

#301 ✨ Feat/#300 서버 배포시 디스코드 알림
  .github/workflows/CD.yml
Labels: 🚀 Deploy

#299 🐛 Fix/#298 학생 참여중인 클래스 조회
  backend/src/main/java/org/example/backend/domain/studentClass/service/StudentClassServiceImpl.java
Labels: 🐛 Bug

#286 🐛 Fix/#283 퀴즈 문제 조회 API 에러
  backend/src/main/java/org/example/backend/domain/quiz/converter/QuizConverter.java
  backend/src/main/java/org/example/backend/domain/quiz/exception/QuizErrorCode.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizServiceImpl.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/converter/QuizResultStudentConverter.java
Labels: 🐛 Bug
