Repository KW-ClassLog/ClassLog, pull requests merged in 2025-07, with the labels that each got.

#247 :recycle: Refactor/#246 카멜케이스로 변경
  backend/src/main/java/org/example/backend/domain/classroom/controller/ClassroomController.java
  backend/src/main/java/org/example/backend/domain/classroom/dto/request/EntryCodeVerifyRequestDTO.java
  backend/src/main/java/org/example/backend/domain/classroom/dto/response/EntryCodeResponseDTO.java
Labels: ♻️ Refactor

#245 🐛 Fix/#224 퀴즈 불가능한 파일과 가능한 파일 함께 있을시 퀴즈 생성 가능하도록 수정
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizServiceImpl.java
Labels: 🐛 Bug

#248 ✨ Feat/#241 학생 목록 불러오기 api 연동
  frontend/api/student-classes/fetchStudentsByClass.ts
  frontend/app/teacher/lecture-management/page.tsx
  frontend/app/teacher/lecturenote-management/page.tsx
  frontend/app/teacher/quiz-management/page.module.scss
  frontend/app/teacher/student-management/page.tsx
  frontend/components/ManagementTable/ManagementTable.tsx
  frontend/components/ManagementTable/_components/StudentRow.tsx
  frontend/constants/endpoints.ts
  frontend/types/student-classes/fetchStudentsByClassTypes.ts
Labels: ✨ Feat
