Repository KW-ClassLog/ClassLog, pull requests merged in 2025-06, with the labels that each got.

#142 ♻️ Refactor/#141 퀴즈 제출 명단 API 도메인 이동
  backend/src/main/java/org/example/backend/domain/quiz/controller/QuizController.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizResultService.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizResultServiceImpl.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/controller/QuizAnswerController.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/dto/response/QuizSubmitListResponseDTO.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/service/QuizAnswerService.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/service/QuizAnswerServiceImpl.java
Labels: ♻️ Refactor

#153 ✨ Feat/#124 퀴즈 대시보드 마크업 개발
  frontend/app/teacher/lecture-management/_components/LectureColumn/LectureColumn.module.scss
  frontend/app/teacher/lecture-management/_components/LectureColumn/LectureColumn.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/BackButtonHeader/BackButtonHeader.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/BackButtonHeader/BackButtonHeader.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/DashboardContainer/DashboardContainer.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/DashboardContainer/DashboardContainer.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/OneLineReview/OneLineReview.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/OneLineReview/OneLineReview.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizInfo/QuizInfo.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizInfo/QuizInfo.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizList/QuizList.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizList/QuizList.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizSubmitList/QuizSubmitList.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizSubmitList/QuizSubmitList.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/AverageCorrectRate/AverageCorrectRate.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/AverageCorrectRate/AverageCorrectRate.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/QuizCorrectRates/QuizCorrectRates.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/QuizCorrectRates/QuizCorrectRates.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/QuizDetailChart/QuizDetailChart.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/QuizDetailChart/QuizDetailChart.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/StatisticsContainer.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/StatisticsContainer.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/page.module.scss
  frontend/app/teacher/quiz-dashboard/[lectureId]/page.tsx
  frontend/app/teacher/quiz-management/_components/LectureItem/LectureItem.tsx
  frontend/config/teacherRouteConfig.ts
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ Feat

#174 🐛 Fix/#173 퀴즈 관련 파라미터 에러 해결
  backend/src/main/java/org/example/backend/domain/quiz/controller/QuizController.java
  backend/src/main/java/org/example/backend/domain/quizAccuracy/controller/QuizAccuracyController.java
  backend/src/main/java/org/example/backend/domain/quizAnswer/controller/QuizAnswerController.java
Labels: 🐛 Bug

#178 🐛 Fix/#177 강의, 강의자료 매핑 에러 해결
  backend/src/main/java/org/example/backend/domain/lecture/controller/LectureController.java
  backend/src/main/java/org/example/backend/domain/lecture/exception/LectureErrorCode.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: 🐛 Bug

#176 ✨ Feat/#167 강의자료 관리 api 연결
  frontend/api/lectures/deleteLectureNote.ts
  frontend/api/lectures/fetchLectureNotesByClass.ts
  frontend/api/lectures/uploadLectureNote.ts
  frontend/app/teacher/lecture-management/page.module.scss
  frontend/app/teacher/lecturenote-management/page.module.scss
  frontend/app/teacher/lecturenote-management/page.tsx
  frontend/components/ManagementTable/ManagementTable.tsx
  frontend/components/ManagementTable/_components/LectureNoteRow.tsx
  frontend/components/ManagementTable/_components/StudentRow.tsx
  frontend/components/Modal/AlertModal/AlertModal.module.scss
  frontend/components/Modal/AlertModal/AlertModal.tsx
  frontend/constants/endpoints.ts
  frontend/types/lectures/fetchLectureNotesByClassTypes.ts
  frontend/types/lectures/uploadLectureNoteTypes.ts
Labels: ✨ Feat

#183 :bug: Bug/#182 강의 맵핑 중복 처리
  backend/src/main/java/org/example/backend/domain/lecture/exception/LectureErrorCode.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
  backend/src/main/java/org/example/backend/domain/lectureNote/service/LectureNoteServiceImpl.java
Labels: 🐛 Bug

#185 :recycle: Refactor/#184 session 계산 로직 수정 및 계산하던 부분 리팩토링
  backend/src/main/java/org/example/backend/domain/lecture/repository/LectureRepository.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ♻️ Refactor

#190 ✨ Feat/#189 강의 조회 response 추가
  backend/src/main/java/org/example/backend/domain/lecture/converter/LectureConverter.java
  backend/src/main/java/org/example/backend/domain/lecture/dto/response/LectureResponseDTO.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ✨ Feat

#186 ✨ Feat/#181 녹음본 기반 퀴즈 생성시 녹음본 없을 경우 에러발생
  backend/src/main/java/org/example/backend/domain/quiz/exception/QuizErrorCode.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizServiceImpl.java
Labels: ✨ Feat

#193 :sparkles: Feat/#192 강의 상세 조회 response 수정
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ✨ Feat

#188 ✨ Feat/#187 퀴즈 생성 불가능 파일 예외처리
  backend/src/main/java/org/example/backend/domain/quiz/exception/QuizErrorCode.java
  backend/src/main/java/org/example/backend/domain/quiz/service/QuizServiceImpl.java
Labels: ✨ Feat

#206 :recycle: Refactor/#204 강의록 맵핑할 때 맵핑되어 있으면 유지, 삭제, 추가 되도록 수정
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ♻️ Refactor

#197 🐛 Fix/#195 타임리프 템플릿 호출 이름 수정
  backend/src/main/java/org/example/backend/domain/user/service/MailServiceImpl.java
Labels: 🐛 Bug

#213 :recycle: Refactor/#212 선생님 오늘의 강의목록 조회에서 session 값 추가
  backend/src/main/java/org/example/backend/domain/lecture/dto/response/TodayLectureResponseDTO.java
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ♻️ Refactor

#210 ♻️ Refactor/#209 모든 강의 목록에서 차시 보여지도록 수정
  frontend/app/teacher/(home)/_components/LectureList/LectureItem.tsx
  frontend/app/teacher/lecture-management/_components/LectureColumn/LectureColumn.tsx
  frontend/app/teacher/quiz-management/page.module.scss
  frontend/types/lectures/fetchLecturesByDate.ts
Labels: ♻️ Refactor

#223 ♻️ Refactor/#221 퀴즈 대시보드 데모데이터 변경
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/DashboardContainer/DashboardContainer.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizInfo/QuizInfo.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizSubmitList/QuizSubmitList.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/StatisticsContainer.tsx
Labels: ♻️ Refactor

#228 :recycle: Refactor/#227 요일 없애기
  backend/src/main/java/org/example/backend/domain/lecture/service/LectureServiceImpl.java
Labels: ♻️ Refactor

#231 ✨ Feat/#230 강의 삭제 api 연동
  frontend/api/lectures/deleteLecture.ts
  frontend/app/teacher/lecture-detail/[lectureId]/_components/BackButtonHeader/BackButtonHeader.module.scss
  frontend/app/teacher/lecture-detail/[lectureId]/_components/BackButtonHeader/BackButtonHeader.tsx
  frontend/app/teacher/lecture-detail/[lectureId]/_components/LectureDetailContainer/LectureDetailContainer.tsx
  frontend/app/teacher/lecture-detail/[lectureId]/page.tsx
Labels: ✨ Feat

#234 🐛 Fix/#233 데모시연 전, 빌드에러 해결
  frontend/app/(non-login)/signup/_components/EmailVerification.tsx
  frontend/app/teacher/lecture-detail/[lectureId]/_components/LectureHeader/LectureHeader.tsx
  frontend/app/teacher/lecture-detail/[lectureId]/_components/LectureMaterials/LectureMaterials.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/DashboardContainer/DashboardContainer.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/OneLineReview/OneLineReview.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/QuizList/QuizList.tsx
  frontend/app/teacher/quiz-dashboard/[lectureId]/_components/StatisticsContainer/StatisticsContainer.tsx
  frontend/app/teacher/quiz-management/page.tsx
  frontend/app/teacher/student-management/page.tsx
  frontend/components/Modal/FileSelectModal/FileSelectModal.tsx
  frontend/components/Modal/MakeInvitationCodeModal/MakeInvitationCodeModal.tsx
Labels: 🐛 Bug
